FROM python:3.11-slim

# Забороняємо Python створювати .pyc файли та буферизувати вивід
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Копіюємо файл залежностей і встановлюємо їх
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо весь код проєкту
COPY . .

# Збираємо статику (тепер файли вже на місці, тому помилки не буде)
RUN python manage.py collectstatic --noinput

# Відкриваємо порт
EXPOSE 8000

# Запускаємо сервер (без квадратних дужок)
CMD gunicorn lms_project.wsgi:application --bind 0.0.0.0:8000